/*
 ADOBE CONFIDENTIAL
 ___________________

 Copyright 2011 Adobe Systems Incorporated
 All Rights Reserved.

 NOTICE:  All information contained herein is, and remains
 the property of Adobe Systems Incorporated and its suppliers,
 if any.  The intellectual and technical concepts contained
 herein are proprietary to Adobe Systems Incorporated and its
 suppliers and may be covered by U.S. and Foreign Patents,
 patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material
 is strictly forbidden unless prior written permission is obtained
 from Adobe Systems Incorporated.
*/
if(typeof Muse=="undefined")window.Muse={};Muse.Assert={};Muse.Assert.fail=function(b){alert("MuseJSAssert: "+b)};$.extend($.browser,{SafariMobile:navigator.userAgent.toLowerCase().match(/iP(hone|ad)/i)});if(!Array.indexOf)Array.prototype.indexOf=function(b){for(var c=0;c<this.length;++c)if(this[c]==b)return c;return-1};Muse.Plugins={};Muse.Utils={};Muse.Utils.addLoadListener=function(b){$(document).ready(b)};
Muse.Utils.runLoadListeners=function(){if(Muse.Utils.loadListeners)for(var b=0;b<Muse.Utils.loadListeners.length;b++)try{Muse.Utils.loadListeners[b]()}catch(c){Muse.Assert.fail("LoadListener failed: "+c)}};Muse.Utils.selectorFns=[];Muse.Utils.addSelectorFn=function(b,c){Muse.Utils.selectorFns.push({selector:b,selFn:c})};
Muse.Utils.addLoadListener(function(){$(Muse.Utils.selectorFns).each(function(){var b=this.selFn,c;try{$(this.selector).each(function(){b(this)})}catch(a){Muse.Assert.fail("Error calling selector function:"+a)}})});
Muse.Utils.getCssVendorPrefix=function(){if(typeof Muse.Utils.getCssVendorPrefix.flag=="undefined")Muse.Utils.getCssVendorPrefix.flag=/webkit/i.test(navigator.appVersion)?"-webkit":/firefox/i.test(navigator.userAgent)?"-moz":/trident/i.test(navigator.userAgent)?"-ms":"opera"in window?"-o":"";return Muse.Utils.getCssVendorPrefix.flag};Muse.Utils.wrapElement=function(b,c){b.parentNode.replaceChild(c,b);c.appendChild(b)};
Muse.Utils.firstChild=function(b,c){for(var a=0;a<b.childNodes.length;a++){var d=b.childNodes[a];if(d.nodeType==1&&(!c||c.matches(d)))return d}return null};Muse.Utils.firstDescendant=function(b,c,a){for(var d=0;d<b.childNodes.length;d++){var f=b.childNodes[d];if(f.nodeType==1){if(!c||c.matches(f))return f;if(!a||!a.matches(f))if(f=Muse.Utils.firstDescendant(f,c,a))return f}}return null};
Muse.Utils.descendants=function(b,c,a,d){if(!d)d=[],d.forEach=function(a){for(var b=0;b<this.length;b++)if(a(this[b]))break},d.forEachTry=function(a){for(var b=0;b<this.length;b++)try{if(a(this[b]))break}catch(d){}};for(var f=0;f<b.childNodes.length;f++){var g=b.childNodes[f];g.nodeType==1&&((!c||c.matches(g))&&d.push(g),(!a||!a.matches(g))&&Muse.Utils.descendants(g,c,a,d))}return d};Muse.Utils.children=function(b,c){return Muse.Utils.descendants(b,c,Muse.Utils.Match.always)};Muse.Utils.Match={};
Muse.Utils.Match.ByClass=function(b){this.cl=b};Muse.Utils.Match.ByClass.prototype.matches=function(b){return $(b).hasClass(this.cl)};Muse.Utils.Match.ByNodeName=function(b){this.nm=b.toLowerCase()};Muse.Utils.Match.ByNodeName.prototype.matches=function(b){return this.nm==b.nodeName.toLowerCase()};Muse.Utils.Match.ByFixed=function(b){this.matchResult=b};Muse.Utils.Match.ByFixed.prototype.matches=function(){return this.matchResult};Muse.Utils.Match.byClass=function(b){return new Muse.Utils.Match.ByClass(b)};
Muse.Utils.Match.byNodeName=function(b){return new Muse.Utils.Match.ByNodeName(b)};Muse.Utils.Match.byFixed=function(b){return new Muse.Utils.Match.ByFixed(b)};Muse.Utils.Match.always=Muse.Utils.Match.byFixed(!0);Muse.Utils.Match.never=Muse.Utils.Match.byFixed(!1);Muse.Utils.moveChildren=function(b,c){for(;b.childNodes.length>0;)c.appendChild(b.childNodes[0])};Muse.Utils.copyChildren=function(b,c){for(var a=0;a<b.childNodes.length;a++)c.appendChild(b.childNodes[a].cloneNode(!0))};
Muse.Utils.copyChildrenBefore=function(b,c){for(var a=0;a<b.childNodes.length;a++)c.parentNode.insertBefore(b.childNodes[a].cloneNode(!0),c)};Muse.Utils.pixelRound=function(b){return Math.floor((b*100+0.5)/100)};Muse.Utils.getCurrentHTMLFileName=function(b){var c=document.location.href;c.charAt(c.length-1)=="/"?c="index":(c=c.substring(c.lastIndexOf("/")+1),c=c.indexOf("#")==0?"index":c.substring(0,c.lastIndexOf(".")));b&&(c+=".html");return c};
Muse.Utils.getPageStyleSheet=function(){for(var b=0;b<document.styleSheets.length;++b){var c=document.styleSheets[b],a=c.ownerNode?c.ownerNode:c.owningElement;if(a&&a.id=="pagesheet")return c}};Muse.Utils.getStyleSheetRuleById=function(b,c){var a=!1,d="#"+c.toLowerCase(),f=b.cssRules;if(!f)a=!0,f=b.rules;if(f)for(var g=0;g<f.length;++g){var i=f[g];if(a){if(i.selectorText.toLowerCase()==d)return i}else if(i.selectorText.toLowerCase().split(", ").indexOf(d)!=-1)return i}return null};
Muse.Utils.getRuleProperty=function(b,c){return b.style.getPropertyValue?b.style.getPropertyValue(c):b.style.getAttribute(c)};Muse.Utils.setRuleProperty=function(b,c,a){b.style.setProperty?b.style.setProperty(c,a,""):b.style.setAttribute(c,a,0)};Muse.Utils.removeRuleProperty=function(b,c){b.style.removeProperty?b.style.removeProperty(c):b.style.removeAttribute(c,0)};
Muse.Utils.cloneStyleSheetRule=function(b){if(typeof Muse.Utils.cloneStyleSheetRule.newNumber=="undefined")Muse.Utils.cloneStyleSheetRule.newNumber=1;var c=Muse.Utils.getPageStyleSheet(b),a=Muse.Utils.getStyleSheetRuleById(c,b),d="c"+Muse.Utils.cloneStyleSheetRule.newNumber++,f="#"+d;c.insertRule?c.insertRule(a.cssText.replace("#"+b,f),c.cssRules.length):c.addRule(f,a.style.cssText);return d};
Muse.Utils.toCamelCase=function(b){for(var c=Muse.Utils.toCamelCase.exp;c.test(b);b=b.replace(c,RegExp.$1.toUpperCase()));return b};Muse.Utils.toCamelCase.exp=/-([a-z])/;Muse.Utils.getStyleValue=function(b,c){var a=b.style[Muse.Utils.toCamelCase(c)];a||(document.defaultView?a=document.defaultView.getComputedStyle(b,"").getPropertyValue(c):b.currentStyle&&(a=b.currentStyle[Muse.Utils.toCamelCase(c)]));a&&a.match(/(\d+)px/)&&(a=parseInt(a.substring(0,a.length-2)));return a};
Muse.Utils.checkCSSFeature=function(b,c){var a=c||Muse.Utils.toCamelCase(b),d=document.createElement("div");if(a in d.style)return!0;for(var a=a.charAt(0).toUpperCase()+a.substr(1,a.length-1),f=0,g=Muse.Utils.checkCSSFeature.domPrefixes.length;f<g;f++)if(Muse.Utils.checkCSSFeature.domPrefixes[f]+a in d.style)return Muse.Utils.checkCSSFeature.domPrefixes[f];return!1};Muse.Utils.checkCSSFeature.domPrefixes="Webkit Moz O ms Khtml".split(" ");
Muse.Utils.checkCSSValueCompatibility=function(b,c){var a=document.createElement("div");if(!(b in a.style))return!1;var d=a.style[b];if(d===c)return!0;for(var f=0;f<Muse.Utils.checkCSSFeature.domPrefixes.length;f++){var g="-"+Muse.Utils.checkCSSFeature.domPrefixes[f].toLowerCase()+"-"+c;a.style[b]=g;if(a.style[b]!==d)return"-"+Muse.Utils.checkCSSFeature.domPrefixes[f].toLowerCase()+"-"}a.style[b]=c;return a.style[b]!==d};
Muse.Utils.urlParam=function(b,c){var a=RegExp("[\\?&]"+c+"=([^&#]*)").exec(b);return a?a[1]:null};
Muse.Utils.processHyperlink=function(b){var c=b.href,a=$(b).attr("target");if(!a||a=="_self"){var a=c.lastIndexOf("/"),d=c.lastIndexOf("#");if((b=$(b).attr("class").match(/anim_(\w+)/))&&d>a){var f=c.substring(d),c=b[1],b=(document.documentElement||document.body).scrollHeight-$(window).height(),a=(document.documentElement||document.body).scrollWidth-$(window).width(),d=Math.min(b,$(f).offset().top),g=Math.min(a,$(f).offset().left);if(!jQuery.browser.msie||jQuery.browser.version>7){var i=[],h=[],j=
[],m=$("html,body"),l={},k=0,n=[],o=!1;i.scrollLeft=0;i.scrollTop=0;h.scrollTop=m.scrollTop();h.scrollLeft=m.scrollLeft();j.scrollTop=[];j.scrollLeft=[];n.scrollTop=!0;n.scrollLeft=!0;if(a>0&&g!==h.scrollLeft)l.scrollLeft=g,k++;if(b>0&&d!==h.scrollTop)l.scrollTop=d,k++;if(!k){window.location.hash=f;return}try{history.pushState({},null,f)}catch(p){}m.animate(l,{duration:1E3,easing:c,step:function(a,b){if(o)b.options.duration=0;else if(n[b.prop]){var d=!1;j[b.prop].push(Math.floor(a));for(var c=j[b.prop].length,
f=j[b.prop].length-8;!d&&c>=0&&c>f;c--)d=Math.abs(j[b.prop][c]-b.elem[b.prop])<=1;Math.abs(a-h[b.prop])<2?i[b.prop]=0:d?0>10*k*2&&i[b.prop]<=1?n[b.prop]=!1:i[b.prop]--:i[b.prop]++;if(i[b.prop]>10)b.options.duration=0,o=!0}},complete:function(){if(o){try{history.replaceState({},null,"#")}catch(a){}setTimeout(function(){window.location.hash=f},16)}else try{history.replaceState({})}catch(b){window.location.hash=f}}})}else $("html,body").animate({scrollTop:d,scrollLeft:g},1E3,c);return!1}}(c=Muse.Utils.urlParam(c,
"devicelock"))&&Muse.Utils.createCookie("devicelock",c,0);return!0};var actionStack=[];Muse.Utils.redirectCancelled=!1;Muse.Utils.redirectHyperlink=function(b){if(Muse.Utils.redirectCancelled)setTimeout(function(){Muse.Utils.redirectCancelled=!1},0);else if(actionStack=[],Muse.Utils.processHyperlink(b)){var c=$(b).attr("target");c||(c="_self");window.open(b.href,c)}};
Muse.Utils.redirectHyperlinkInNewTab=function(b,c){if(Muse.Utils.redirectCancelled)setTimeout(function(){Muse.Utils.redirectCancelled=!1},0);else{actionStack=[];thisWindow=window.self;var a=window.open(b);c?a.focus():thisWindow.focus()}};Muse.Utils.isMouseLeftClick=function(b){return b.which==1};Muse.Utils.isMouseMiddleClick=function(b){return b.which==2};Muse.Utils.isRedirectLinkKeyboardAction=function(b){return b.which==13};
Muse.Utils.addHyperlinkAnchor=function(b){b=$(b);b.bind("mousedown",function(b){(Muse.Utils.isMouseLeftClick(b)||Muse.Utils.isMouseMiddleClick(b))&&actionStack.push(this)});b.bind("mouseup keyup",function(b){if(Muse.Utils.isMouseLeftClick(b)&&actionStack.indexOf(this)!=-1)b.ctrlKey||b.metaKey?Muse.Utils.redirectHyperlinkInNewTab(this.href,b.shiftKey):Muse.Utils.redirectHyperlink(this);else if(Muse.Utils.isMouseMiddleClick(b)&&actionStack.indexOf(this)!=-1)if(jQuery.browser.webkit||!b.target.href&&
jQuery.browser.msie)Muse.Utils.redirectHyperlinkInNewTab(this.href,b.shiftKey);else return actionStack=[],!0;else Muse.Utils.isRedirectLinkKeyboardAction(b)&&Muse.Utils.redirectHyperlink(this);return!1});b.bind("click",function(){return!1})};
Muse.Utils.addHyperlinkBlock=function(b){var c=$(b.parentNode);c.bind("mousedown",function(a){(Muse.Utils.isMouseLeftClick(a)||Muse.Utils.isMouseMiddleClick(a))&&actionStack.push(this);return!1});c.bind("mouseup keyup",function(a){Muse.Utils.isMouseLeftClick(a)&&actionStack.indexOf(this)!=-1?a.ctrlKey||a.metaKey?Muse.Utils.redirectHyperlinkInNewTab(b.href,a.shiftKey):Muse.Utils.redirectHyperlink(b):Muse.Utils.isMouseMiddleClick(a)&&actionStack.indexOf(this)!=-1?Muse.Utils.redirectHyperlinkInNewTab(b.href,
a.shiftKey):Muse.Utils.isRedirectLinkKeyboardAction(a)&&Muse.Utils.redirectHyperlink(b);return!1});c.bind("click",function(){return!1})};
Muse.Utils.prepHyperlinks=function(){var b={};$("a.block").each(function(){var c=$(this.parentNode);Muse.Utils.addHyperlinkBlock(this);c.find("a.nonblock").each(function(){if(b[this.id]==!0)return!1;Muse.Utils.addHyperlinkAnchor(this);b[this.id]=!0})});$("a.nonblock").each(function(){if(b[this.id]!=!0){var c=$(this);c.parent('[class~="sbg"]').length>0?Muse.Utils.addHyperlinkAnchor(this):(c.attr("class").match(/anim_(\w+)/)||this.href.indexOf("devicelock=")!=-1)&&$(this).bind("click",function(){return Muse.Utils.processHyperlink(this)})}})};
Muse.Utils.getNaturalWidth=function(b){var c=-1;b.naturalWidth!=null?c=b.naturalWidth:b.runtimeStyle?(b.runtimeStyle.width="auto",b.runtimeStyle.height="auto",b.runtimeStyle.borderWidth="0",b.runtimeStyle.padding="0",c=b.offsetWidth,b.runtimeStyle.width="",b.runtimeStyle.height="",b.runtimeStyle.borderWidth="",b.runtimeStyle.padding=""):(b=b.cloneNode(!0),b.className="",b.style.width="auto !important",b.style.height="auto !important",b.style.borderWidth="0 !important",b.style.padding="0 !important",
c=b.width);return c};
Muse.Utils.getNaturalHeight=function(b){var c=-1;b.naturalHeight!=null?c=b.naturalHeight:b.runtimeStyle?(b.runtimeStyle.width="auto",b.runtimeStyle.height="auto",b.runtimeStyle.borderWidth="0",b.runtimeStyle.padding="0",c=b.offsetHeight,b.runtimeStyle.width="",b.runtimeStyle.height="",b.runtimeStyle.borderWidth="",b.runtimeStyle.padding=""):(b=b.cloneNode(!0),b.className="",b.style.width="auto !important",b.style.height="auto !important",b.style.borderWidth="0 !important",b.style.padding="0 !important",
c=b.height);return c};Muse.Utils.needPIE=function(){if(!Muse.Utils.havePIE)$.ajax({url:"scripts/1.1/pie.js",dataType:"script",async:!1}),Muse.Utils.havePIE=!0};Muse.Utils.transformMarkupToFixBrowserProblemsPreInit=function(){jQuery.browser.msie?(jQuery("html").addClass("ie"),jQuery.browser.version<8&&Muse.Utils.changeLItoDIVs()):jQuery.browser.SafariMobile&&jQuery("body").css("-webkit-text-size-adjust","none")};
Muse.Utils.transformMarkupToFixBrowserProblems=function(){Muse.Utils.havePIE=!1;jQuery.browser.msie&&(jQuery.browser.version<=9&&(Muse.Utils.addGradientFill(),Muse.Utils.addShadows()),jQuery.browser.version<9&&(Muse.Utils.applyIEFilterToPNGImages(),Muse.Utils.addRoundedCorners(),Muse.Utils.addRGBA(),Muse.Utils.removeEdgeAnimationBorderForIE78()),jQuery.browser.version<8&&Muse.Utils.fixWidthsForClearingInIE7());(jQuery.browser.msie&&jQuery.browser.version<9||jQuery.browser.webkit)&&Muse.Utils.insertEmptyDivAfterPinnedColumnElements()};
Muse.Utils.applyIEFilterToPNGImages=function(){jQuery.browser.msie&&jQuery.browser.version<9&&$("body *").not(".museBgSizePolyfill img").each(function(){var b=$(this);if(b.css("background-image").match(/\b.png/i)||this.nodeName&&this.nodeName.toLowerCase()=="img"&&b.attr("src").match(/\b.png/i)){var c=b.css("filter");b.css("filter",c?c+" progid:DXImageTransform.Microsoft.gradient(startColorstr=#00FFFFFF,endColorstr=#00FFFFFF)":"progid:DXImageTransform.Microsoft.gradient(startColorstr=#00FFFFFF,endColorstr=#00FFFFFF)")}})};
Muse.Utils.insertEmptyDivAfterPinnedColumnElements=function(){$(".pinned-colelem").each(function(){$("<div class='colelem'/>").insertAfter($(this))})};Muse.Utils.fixPNGImages=function(){$("body *").each(function(){var b=$(this);if(b.css("background-image").match(/\b.png/i)||this.nodeName&&this.nodeName.toLowerCase()=="img"&&b.attr("src").match(/\b.png/i))Muse.Utils.needPIE(),b.css("-pie-png-fix","true"),PIE.attach(this)})};
Muse.Utils.addGradientFill=function(){$(".gradient").each(function(){Muse.Utils.needPIE();PIE.attach(this)})};Muse.Utils.addShadows=function(){$(".shadow").each(function(){Muse.Utils.needPIE();PIE.attach(this)})};
Muse.Utils.addRoundedCorners=function(){$(".rounded-corners").each(function(){Muse.Utils.needPIE();var b=$(this);if(jQuery.browser.msie&&jQuery.browser.version<8&&(b.css("border-left-width")==0||b.css("border-left-style")=="none")&&(b.css("border-right-width")==0||b.css("border-right-style")=="none")&&(b.css("border-top-width")==0||b.css("border-top-style")=="none")&&(b.css("border-bottom-width")==0||b.css("border-bottom-style")=="none"))b.css({"border-right-width":"1px","border-right-style":"solid",
"border-right-color":b.css("background-color")}),b.width(b.width()-1);PIE.attach(this)})};Muse.Utils.addRGBA=function(){$(".rgba-background").each(function(){Muse.Utils.needPIE();PIE.attach(this)})};Muse.Utils.fixWidthsForClearingInIE7=function(){$(".colelem").each(function(){var b=$(this).offset().left-$(this).parent().offset().left;if($(this).width()<1||$(this).width()+b<1)$(this).css("width",(b<0?1-b:1)+"px")})};
Muse.Utils.removeEdgeAnimationBorderForIE78=function(){$(".animationContainer").each(function(){$(this).parent().html(function(b,c){return c.replace(/><\/iframe>$/gi,' frameBorder="0"></iframe>')})})};Muse.Utils.fixAnimationsMarkup=function(){$(".animationContainer").each(function(){var b=$(this);b.load(function(){var c=b.contents();$("#report-abuse",c).remove();$("#report-abuse-spacer",c).remove()})})};
Muse.Utils.fullPage=function(b){var c=$(b+" .verticalspacer"),a=$(b),d=$(window),f=$("body"),g=Muse.Utils.getCSSIntValue(f,"padding-top")+Muse.Utils.getCSSIntValue(f,"margin-top"),i=Muse.Utils.getCSSIntValue(f,"padding-bottom")+Muse.Utils.getCSSIntValue(f,"margin-bottom"),h=!0,j=function(){var b=a.outerHeight(!0)-c.height(),b=d.height()-g-i-b+1;0<b?f.addClass("no_vert_scroll"):f.removeClass("no_vert_scroll");h=!1;c.css("height",Math.max(1,b));h=!0};a.watch("height",function(){h&&j()});d.resize(j);
$(document).ready(j)};Muse.Utils.getCSSIntValue=function(b,c){var a=parseInt(b.css(c));isNaN(a)&&(a=0);return a};Muse.Utils.changeLItoDIVs=function(){var b=function(){var b=$(this),a=$("<div/>");a.addClass(b.attr("class"));a.attr("id",b.attr("id"));a.append(b.contents());b.replaceWith(a)};$("ul").each(function(){$(this).find("li").each(b)});$("ul").each(b)};Muse.Utils.showWidgetsWhenReady=function(){jQuery(".disn").removeClass("disn");jQuery(".invi").removeClass("invi");jQuery(".widget_invisible").removeClass("widget_invisible")};
Muse.Utils.detachIframesAndObjectsToPauseMedia=function(b){var c=[];$("iframe, object",b).each(function(){var a=$(this);if(!a.is("object")||!(jQuery.browser.msie&&jQuery.browser.version<9)){var b={};b.$next=a.next();b.$parent=a.parent();jQuery.browser.msie?(b.html=a.wrap("<div id='deleteMeWrapper'/>").parent().html(),a.remove(),b.$parent.children("div #deleteMeWrapper").remove()):b.$node=a.detach();c.push(b)}});c.length&&b.data("detached",c);$("video",b).each(function(){if(jQuery.browser.msie&&jQuery.browser.version==
9&&this.pause&&this.getAttribute("autoplay")&&this.readyState!=4)$(this).one("play",function(){this.pause()});else this.pause&&!this.paused&&this.pause()})};
Muse.Utils.attachIframesAndObjectsToResumeMedia=function(b){var c=b.data("detached");if(c){for(var a=c.length-1;a>=0;a--){var d=c[a];!d.$next||d.$next.length==0?d.$parent.append(d.$node?d.$node:d.html):d.$next.before(d.$node?d.$node:d.html);d.$next=d.$parent=d.$node=d.html=void 0}b.data("detached",null)}$("video",b).each(function(){if(this.play&&this.getAttribute("autoplay")&&this.paused)this.currentTime=0,this.play()})};
Muse.Utils.createCookie=function(b,c,a){if(a){var d=new Date;d.setTime(d.getTime()+a*864E5);a="; expires="+d.toGMTString()}else a="";document.cookie=b+"="+c+a+"; path=/"};Muse.Utils.readCookie=function(b){b+="=";for(var c=document.cookie.split(";"),a=0;a<c.length;a++){for(var d=c[a];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(b)==0)return d.substring(b.length,d.length)}return null};Muse.Utils.eraseCookie=function(b){createCookie(b,"",-1)};Muse.Browser={};
Muse.Browser.domPrefixes=["Webkit","Moz","O","ms","Khtml"];Muse.Browser.Features={};
Muse.Browser.Features.Touch=function(){if(navigator.maxTouchPoints>0)return{Start:"pointerDown",End:"pointerUp",Move:"pointerMove",Listener:function(a){return function(b){var d=b.originalEvent||b;if(d.pointerType!=d.POINTER_TYPE_MOUSE)return a.apply(this,arguments)}}};else for(var b=0,c=Muse.Browser.domPrefixes.length;b<c;b++){var a=Muse.Browser.domPrefixes[b];if(a+"MaxTouchPoints"in navigator&&navigator[a+"MaxTouchPoints"])return a=a.toUpperCase(),{Start:a+"PointerDown",End:a+"PointerUp",Move:a+
"PointerMove",Listener:function(b){return function(d){var c=d.originalEvent||d;if(c.pointerType!=c[a+"POINTER_TYPE_MOUSE"])return b.apply(this,arguments)}}}}try{return document.createEvent("TouchEvent"),{Start:"touchstart",End:"touchend",Move:"touchmove",Listener:function(a){return a}}}catch(d){}return!1}();
Muse.Browser.Features.checkCSSFeature=function(b,c){var a=Muse.Utils.toCamelCase(b),c=c||document.createElement("div");if(a in c.style)return!0;for(var a=a.charAt(0).toUpperCase()+a.substr(1,a.length-1),d=0,f=Muse.Browser.domPrefixes.length;d<f;d++)if(Muse.Browser.domPrefixes[d]+a in c.style)return Muse.Browser.domPrefixes[d];return!1};
Muse.Browser.Features.checkCSSValueCompatibility=function(b,c){var a=document.createElement("div"),b=Muse.Utils.toCamelCase(b),d=Muse.Browser.Features.checkCSSFeature(b);if(d)d!==!0&&(b=d+b.charAt(0).toUpperCase()+b.substr(1,b.length-1));else return!1;d=a.style[b];a.style[b]=c;if(d===c)return!0;for(var f=0;f<Muse.Browser.domPrefixes.length;f++){var g="-"+Muse.Browser.domPrefixes[f].toLowerCase()+"-"+c;a.style[b]=g;if(a.style[b]!==d)return Muse.Browser.domPrefixes[f]}return!1};Muse.Browser.Bugs={};
Muse.Browser.Bugs.ClearNeedsOuterWidth=function(){var b=document.createElement("div");b.id="mbbcnow00";b.innerHTML='<div>a</div><style type="text/css">#mbbcnow00{position:absolute;top:-9999px;left:-9999px;visibility:hidden;} #mbbcnow01{width:1px;margin-right:-9999px;float:left} #mbbcnow02{clear:left;}</style>';var c=document.createElement("div"),a=document.createElement("div");document.body.appendChild(b);b.appendChild(c);b.appendChild(a);c.innerHTML="a";c.id="mbbcnow01";a.innerHTML="b";a.id="mbbcnow02";
c=a.getBoundingClientRect().top-c.getBoundingClientRect().top;document.body.removeChild(b);return c<1}();
