/*

 Copyright (c) 2012. Adobe Systems Incorporated.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of Adobe Systems Incorporated nor the names of its
 contributors may be used to endorse or promote products derived from this
 software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.
*/
(function(b,c){function a(){}var d={version:0.1,inherit:function(a,d){var b=function(){};b.prototype=d.prototype;a.prototype=new b;a.prototype.constructor=a;a.prototype._super=d},ensureArray:function(){var a=[],d=arguments.length;d>0&&(a=d>1||!b.isArray(arguments[0])?b.makeArray(arguments):arguments[0]);return a},scopedFind:function(a,d,c,i){for(var c=" "+c+" ",j=[],a=b(a).find(d),d=a.length,i=b(i)[0],m=0;m<d;m++)for(var l=a[m],k=l;k;){if(k.className&&(" "+k.className+" ").indexOf(c)!==-1){k===i&&
j.push(l);break}k=k.parentNode}return b(j)}};b.extend(a.prototype,{bind:function(a,d,c){return b(this).bind(a,d,c)},unbind:function(a,d){return b(this).unbind(a,d)},trigger:function(a,d){var c=b.Event(a);b(this).trigger(c,d);return c}});d.EventDispatcher=a;c.WebPro=d})(jQuery,window,document);
(function(b,c){var a=1;c.ImageLoader=function(a){c.EventDispatcher.call();var f=this;this.options=b.extend({},this.defaultOptions,a);this._currentEntry=null;this._queue=[];this._isRunning=this._needsSort=!1;this._loader=new Image;this._loadFunc=function(){f._handleLoad()};this._loadErrorFunc=function(){f._handleError()};this._timeoutFunc=function(){f.trigger("wp-image-loader-timeout",this._currentEntry);f._loadNext()}};c.inherit(c.ImageLoader,c.EventDispatcher);b.extend(c.ImageLoader.prototype,{defaultOptions:{timeoutInterval:1E3},
add:function(d,f){if(d){urls=c.ensureArray(d);for(var g=0;g<urls.length;g++){var h=b.extend({reqId:a++,src:urls[g],width:0,height:0,priority:50,callback:null,data:null},f);this._queue.push(h);this._needsSort=!0;this.trigger("wp-image-loader-add",h)}this._isRunning&&!this._currentEntry&&this._loadNext()}},reprioritize:function(a,b){if(!(this._currentEntry&&this._currentEntry.src==a)){var c;for(c=0;c<this._queue.length;++c)if(this._queue[c].src==a)break;if(c!=0&&c<this._queue.length)this._queue=this._queue.splice(c,
b?this._queue.length-c:1).concat(this._queue)}},start:function(){if(!this._isRunning)this._isRunning=!0,this._loadNext(),this.trigger("wp-image-loader-start")},stop:function(){if(this._isRunning)this._currentEntry&&this._queue.unshift(this._currentEntry),this._resetLoader(),this._isRunning=!1,this.trigger("wp-image-loader-stop")},clearQueue:function(){var a=this._isRunning;this.stop();this._queue.length=0;a&&this.start()},isQueueEmpty:function(){return this._queue.length==0},_loadNext:function(){var d;
this._resetLoader();var a=this._queue;if(a.length){if(this._needsSort)d=this._queue=a.sort(function(a,d){var b=a.priority-d.priority;return b?b:a.reqId-d.reqId}),a=d,this._needsSort=!1;this._currentEntry=a=a.shift();var b=this._loader;b.onload=this._loadFunc;b.onerror=this._loadErrorFunc;b.src=a.src}},_resetLoader:function(){var a=this._loader;a.onload=null;a.onerror=null;this._currentEntry=a.src=null;if(this._timeoutTimerId)clearTimeout(this._timeoutTimerId),this._timeoutTimerId=0},_handleLoad:function(){var a=
this._loader,b=this._currentEntry;b.width=a.width;b.height=a.height;b.callback&&b.callback(b.src,b.width,b.height,b.data);this.trigger("wp-image-loader-load-success",b);this._loadNext()},_handleError:function(){this.trigger("wp-image-loader-load-error",this._currentEntry);this._loadNext()}})})(jQuery,WebPro,window,document);
(function(b,c){function a(){c.EventDispatcher.call(this);this._initialize.apply(this,arguments)}c.inherit(a,c.EventDispatcher);b.extend(a.prototype,{defaultOptions:{},_widgetName:"Widget",_initialize:function(){var a;this.plugins=[];var f=this.trigger("before-setup");f.isDefaultPrevented()||(a=this._setUp.apply(this,arguments),this.trigger("setup"));f=this.trigger("before-init-plugins");f.isDefaultPrevented()||(this._initializePlugins(a),this.trigger("init-plugins"));this.options=b.extend({},this.defaultOptions,
a);f=this.trigger("before-extract-data");f.isDefaultPrevented()||(this._extractData(),this.trigger("extract-data"));f=this.trigger("before-transform-markup");f.isDefaultPrevented()||(this._transformMarkup(),this.trigger("transform-markup"));f=this.trigger("before-attach-behavior");f.isDefaultPrevented()||(this._attachBehavior(),this.trigger("attach-behavior"));f=this.trigger("before-ready");f.isDefaultPrevented()||(this._ready(),this.trigger("ready"))},_setUp:function(a,f){this.$element=b(a);return f},
_initializePlugins:function(a){for(var a=a||{},b=((typeof a.useDefaultPlugins==="undefined"||a.useDefaultPlugins)&&this.defaultPlugins?this.defaultPlugins:[]).concat(a.plugins||[]),b=b.sort(function(a,d){a=typeof a.priority==="number"?a.priority:50;d=typeof d.priority==="number"?d.priority:50;return a-d}),c=0;c<b.length;c++){var h=b[c];h&&h.initialize&&h.initialize(this,a)}this.plugins=b},_extractData:function(){},_transformMarkup:function(){},_attachBehavior:function(){},_ready:function(){}});c.Widget=
a;c.widget=function(a,f,g){var h=g&&f||c.Widget,g=g||f||{},f=function(){h.apply(this,arguments);this._widgetName=a};c.inherit(f,h);b.extend(f.prototype,g);f.prototype.defaultOptions=b.extend({},h.prototype.defaultOptions,g.defaultOptions);var g=a.split("."),i=g.length;namespace=i>1&&g[0]||"Widget";a=g[i-1];c[namespace][a]=f}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.Button",c.Widget,{defaultOptions:{hoverClass:"wp-button-hover",activeClass:"wp-button-down",disabledClass:"wp-button-disabled",disabled:!1,callback:null},_attachBehavior:function(){var a=this,d=function(f){a.mouseDown=!1;a.$element.removeClass(a.options.activeClass);!a.options.disabled&&a.options.callback&&a.options.callback.call(this,f);b(a.$element).off("mouseup",d)};this.mouseDown=!1;this.$element.on("mouseover",function(){a.options.disabled||a.$element.addClass(a.options.hoverClass+
(a.mouseDown?" "+a.options.activeClass:""))}).on("mouseout",function(){a.$element.removeClass(a.options.hoverClass+" "+a.options.activeClass);b(a.$element).off("mouseup",d)}).on("mousedown",function(){if(!a.options.disabled)a.mouseDown=!0,a.$element.addClass(a.options.activeClass),b(a.$element).on("mouseup",d)});this.disabled(this.options.disabled)},disabled:function(a){if(typeof a==="boolean")this.options.disabled=a,this.$element[a?"addClass":"removeClass"](this.options.disabledClass);return this.options.disabled}});
b.fn.wpButton=function(a){this.each(function(){new c.Widget.Button(this,a)});return this}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.RadioGroup",c.Widget,{_widgetName:"radio-group",defaultOptions:{defaultIndex:0,hoverClass:"wp-radio-hover",downClass:"wp-radio-down",disabledClass:"wp-radio-disabled",checkedClass:"wp-radio-checked",disabled:!1,toggleStateEnabled:!1},_attachBehavior:function(){var a=this;this.buttons=[];this.activeElement=null;this.activeIndex=-1;this.$element.each(function(){a.buttons.push(a._addButtonBehavior(this))});this.disabled(this.options.disabled)},_addButtonBehavior:function(a){var d=
this,b=new c.Widget.Button(a,{hoverClass:this.options.hoverClass,downClass:this.options.downClass,disabledClass:this.options.disabledClass,callback:function(c){return d._handleClick(c,b,a)}});return b},_handleClick:function(a,d,b){this.options.disabled||this.checkButton(b)},_getElementIndex:function(a){return a?b.inArray(a,this.$element.get()):-1},_getElementByIndex:function(a){return a>=0?this.$element.eq(a)[0]:null},_getElement:function(a){return typeof a==="number"?this._getElementByIndex(a):a},
checkButton:function(a){var a=this._getElement(a),d=this.activeElement,f=this.options.checkedClass;a!==d?(d&&b(d).removeClass(f),a&&b(a).addClass(f)):this.options.toggleStateEnabled&&a&&(b(a).removeClass(f),a=null);this.activeElement=a;this.activeIndex=this._getElementIndex(a)},disabled:function(a){if(typeof a==="boolean")this.disabled=a,b.each(this.buttons,function(){this.disabled(a)});return this.options.disabled}});b.fn.wpRadioGroup=function(a){new c.Widget.RadioGroup(this,a);return this}})(jQuery,
WebPro,window,document);
(function(b,c){c.widget("Widget.TabGroup",c.Widget.RadioGroup,{defaultOptions:{defaultIndex:0,hoverClass:"wp-tab-hover",downClass:"wp-tab-down",disabledClass:"wp-tab-disabled",checkedClass:"wp-tab-active",disabled:!1,toggleStateEnabled:!1},selectTab:function(a){this.checkButton(a)},checkButton:function(a){var d=this._getElement(a),b=this._getElementIndex(d),d={tab:d,tabIndex:b};this.trigger("wp-tab-before-select",d);this._super.prototype.checkButton.apply(this,arguments);this.trigger("wp-tab-select",d)}});
b.fn.wpTabGroup=function(a){new c.Widget.TabGroup(this,a);return this}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.PanelGroup",c.Widget,{_widgetName:"panel-group",defaultOptions:{defaultIndex:0,panelClass:"wp-panel",activeClass:"wp-panel-active",toggleStateEnabled:!1,tabGroups:null},_setUp:function(){var a=this;this.tabGroups=[];this._tabCallback=function(d,b){a._handleTabSelect(d,b)};this.showLock=0;this.tabDriver=null;return this._super.prototype._setUp.apply(this,arguments)},_attachBehavior:function(){this.activeElement=null;this.activeIndex=-1;this.$element.addClass(this.options.panelClass);
var a=this.options.defaultIndex;typeof a==="number"&&a>=0&&this.showPanel(a);this.addTabGroup(this.options.tabGroups)},_getElementIndex:function(a){return a?b.inArray(a,this.$element.get()):-1},_getElementByIndex:function(a){return this.$element.eq(a)[0]},_getElement:function(a){return typeof a==="number"?this._getElementByIndex(a):a},showPanel:function(a){if(!this.showLock){++this.showLock;var d=this._getElement(a),f=this.activeElement,c=this.options.activeClass;if(d)if(d!==f){a={panel:d,panelIndex:this._getElementIndex(d)};
this.trigger("wp-panel-before-show",a);f&&this.hidePanel(f);b(d).addClass(c);this.activeElement=d;this.activeIndex=this._getElementIndex(d);d=this.tabGroups;for(f=0;f<d.length;f++)c=d[f],c!==this.tabDriver&&c.selectTab(this.activeIndex);this.trigger("wp-panel-show",a)}else this.options.toggleStateEnabled&&this.hidePanel(d);--this.showLock}},hidePanel:function(a){if(a=typeof a==="number"?this.$element.eq(a)[0]:a){var d={panel:a,panelIndex:this._getElementIndex(a)};this.trigger("wp-panel-before-hide",
d);b(a).removeClass(this.options.activeClass);if(a===this.activeElement)this.activeElement=null,this.activeIndex=-1;this.trigger("wp-panel-hide",d)}},_handleTabSelect:function(a,d){if(!this.showLock)this.tabDriver=a.target,this.showPanel(d.tabIndex),this.tabDriver=null},addTabGroup:function(a){if(a)for(var a=c.ensureArray(a),d=a.length,f=0;f<d;f++){var g=a[f];b.inArray(this.tabGroups,g)===-1&&(this.tabGroups.push(g),g.selectTab(this.activeIndex),g.bind("wp-tab-select",this._tabCallback))}},removeTabGroup:function(a){for(var a=
c.ensureArray(a),d=a.length,f=0;f<d;f++){var g=a[f];sets=this.tabGroups;loc=b.inArray(sets,g);loc!==-1&&sets.splice(loc,1)}}});b.fn.wpPanelGroup=function(a){new c.Widget.PanelGroup(this,a);return this}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.Disclosure",c.Widget,{defaultOptions:{widgetClassName:"wp-disclosure-panels",tabClassName:"wp-disclosure-panels-tab",tabHoverClassName:"wp-disclosure-panels-tab-hover",tabDownClassName:"wp-disclosure-panels-tab-down",panelClassName:"wp-disclosure-panels-panel",tabActiveClassName:"wp-disclosure-panels-tab-active",panelActiveClassName:"wp-disclosure-panels-panel-active",defaultIndex:0,toggleStateEnabled:!1},_attachBehavior:function(){var a=this.$element[0],d=this.options.widgetClassName,
b=c.scopedFind(a,"."+this.options.tabClassName,d,a),a=c.scopedFind(a,"."+this.options.panelClassName,d,a);this.tabs=new c.Widget.TabGroup(b,{hoverClass:this.options.tabHoverClassName,downClass:this.options.tabDownClassName,checkedClass:this.options.tabActiveClassName,toggleStateEnabled:this.options.toggleStateEnabled});this.panels=new c.Widget.PanelGroup(a,{panelClass:this.options.panelClassName,activeClass:this.options.panelActiveClassName,defaultIndex:this.options.defaultIndex,toggleStateEnabled:this.options.toggleStateEnabled});
this.panels.addTabGroup(this.tabs)}});c.widget("Widget.TabbedPanels",c.Widget.Disclosure,{defaultOptions:{widgetClassName:"wp-tabbed-panels-panels",tabClassName:"wp-tabbed-panels-panels-tab",tabHoverClassName:"wp-tabbed-panels-panels-tab-hover",tabDownClassName:"wp-tabbed-panels-panels-tab-down",tabActiveClassName:"wp-tabbed-panels-panels-tab-active",panelClassName:"wp-tabbed-panels-panels-panel",panelActiveClassName:"wp-tabbed-panels-panels-panel-active",toggleStateEnabled:!1}});c.widget("Widget.Accordion",
c.Widget.Disclosure,{defaultOptions:{widgetClassName:"wp-accordion",tabClassName:"wp-accordion-tab",tabHoverClassName:"wp-accordion-tab-hover",tabDownClassName:"wp-accordion-tab-down",tabActiveClassName:"wp-accordion-tab-active",panelClassName:"wp-accordion-panel",panelActiveClassName:"wp-accordion-panel-active",toggleStateEnabled:!1}})})(jQuery,WebPro,window,document);
(function(b,c){c.Widget.Disclosure.DisplayPropertyTransitionPlugin={defaultOptions:{},initialize:function(a,d){var f=this;b.extend(d,b.extend({},f.defaultOptions,d));a.bind("attach-behavior",function(){f._attachBehavior(a)})},_attachBehavior:function(a){var a=a.panels,d=a.$element,b=a.activeIndex;a.bind("wp-panel-show",function(a,d){d.panel.style.display="block"});a.bind("wp-panel-hide",function(a,d){d.panel.style.display="none"});d.each(function(a){this.style.display=a!==b?"none":"block"})}};c.Widget.Disclosure.AccordionTransitionPlugin=
{defaultOptions:{transitionDirection:"vertical",transitionDuration:500},initialize:function(a,d){var f=this;b.extend(d,b.extend({},f.defaultOptions,d));a.bind("attach-behavior",function(){f._attachBehavior(a)})},_attachBehavior:function(a){var d=this,b=a.panels,c=b.$element,h=b.activeIndex,i=a.options.transitionDirection;c.css("overflow","hidden");b.bind("wp-panel-show",function(b,f){d._showPanel(a,f)});b.bind("wp-panel-hide",function(b,f){d._hidePanel(a,f)});c.each(function(a){if(a!==h){if(i==="vertical"||
i==="both")this.style.height="0";if(i==="horizontal"||i==="both")this.style.width="0"}})},_showPanel:function(a,d){var f=a.options,c=f.transitionDirection,h=b(d.panel),i={};if(c==="vertical"||c==="both")i.height=h[0].scrollHeight+"px";if(c==="horizontal"||c==="both")i.width=h[0].scrollWidth+"px";h.stop(!0,!0).animate(i,{duration:f.transitionDuration,complete:function(){var a={};if(c==="vertical"||c==="both")a.height="auto";if(c==="horizontal"||c==="both")a.width="auto";h.css(a)}})},_hidePanel:function(a,
d){var f=a.options,c=f.transitionDirection,h=b(d.panel),i={};if(c==="vertical"||c==="both")i.height="0";if(c==="horizontal"||c==="both")i.width="0";h.stop(!0,!0).animate(i,{duration:f.transitionDuration})}}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.SlideShowBase",c.Widget,{_widgetName:"slideshow-base",defaultOptions:{displayInterval:6E3,autoPlay:!1},_setUp:function(){var a=this;this._ssTimer=0;this._ssTimerTriggered=!1;this._ssTimerCallback=function(){a._ssTimerTriggered=!0;a.next();a._ssTimerTriggered=!1};return c.Widget.prototype._setUp.apply(this,arguments)},_ready:function(){this.options.autoPlay&&this.play()},play:function(){e=this.trigger("wp-slideshow-before-play");e.isDefaultPrevented()||(this._startTimer(),
this.trigger("wp-slideshow-play"))},stop:function(){e=this.trigger("wp-slideshow-before-stop");e.isDefaultPrevented()||(this._stopTimer(),this.trigger("wp-slideshow-stop"))},isPlaying:function(){return this._ssTimer!==0},_startTimer:function(){this._stopTimer();this._ssTimer=setTimeout(this._ssTimerCallback,this.options.displayInterval)},_stopTimer:function(){this._ssTimer&&clearTimeout(this._ssTimer);this._ssTimer=0},_executeCall:function(a,d){e=this.trigger("wp-slideshow-before-"+a);e.isDefaultPrevented()||
(this["_"+a].apply(this,d)&&this.stop(),this.isPlaying()&&this._startTimer(),this.trigger("wp-slideshow-"+a))},first:function(){return this._executeCall("first",arguments)},last:function(){return this._executeCall("last",arguments)},previous:function(){return this._executeCall("previous",arguments)},next:function(){return this._executeCall("next",arguments)},goTo:function(){return this._executeCall("goTo",arguments)},_first:function(){},_last:function(){},_previous:function(){},_next:function(){},
_goTo:function(){}})})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.ContentSlideShow",c.Widget.SlideShowBase,{_widgetName:"content-slideshow",defaultOptions:{slideshowClassName:"wp-slideshow",clipClassName:"wp-slideshow-clip",viewClassName:"wp-slideshow-view",slideClassName:"wp-slideshow-slide",slideLinkClassName:"wp-slideshow-slide-link",firstBtnClassName:"wp-slideshow-first-btn",lastBtnClassName:"wp-slideshow-last-btn",prevBtnClassName:"wp-slideshow-prev-btn",nextBtnClassName:"wp-slideshow-next-btn",playBtnClassName:"wp-slideshow-play-btn",
stopBtnClassName:"wp-slideshow-stop-btn",playingClassName:"wp-slideshow-playing"},_findWidgetElements:function(a){var d=this.$element[0];return c.scopedFind(d,a,this.options.slideshowClassName,d)},_attachBtnHandler:function(a,d){var b=this;this["$"+d+"Btn"]=this._findWidgetElements("."+a).bind("click",function(a){b[d]();a.preventDefault()})},_reprioritizeImageLoadingIfRequired:function(a){!this._isLoaded(a)&&this._cssilLoader&&!this._cssilLoader.isQueueEmpty()&&this._cssilLoader.reprioritize(b(this.slides.$element[a]).find("img").data("src"),
this.isPlaying())},_attachBehavior:function(){var a=this,d=this.options;this._super.prototype._attachBehavior.call(this);this._panelShowCallback=function(){a._ssTimerTriggered||a.isPlaying()&&a._startTimer()};this.$element.addClass(d.slideshowClassName);var b=this._findWidgetElements("."+d.slideClassName),g=this._findWidgetElements("."+d.slideLinkClassName);this.slides=new c.Widget.PanelGroup(b,{defaultIndex:d.defaultIndex||0});this.slides.bind("wp-panel-show",this._panelShowCallback);this.tabs=null;
if(g.length)this.tabs=new c.Widget.TabGroup(g,{defaultIndex:d.defaultIndex||0}),this.slides.addTabGroup(this.tabs);this.slides.bind("wp-panel-before-show",function(d,b){a._reprioritizeImageLoadingIfRequired(b.panelIndex)});this._attachBtnHandler(d.firstBtnClassName,"first");this._attachBtnHandler(d.lastBtnClassName,"last");this._attachBtnHandler(d.prevBtnClassName,"previous");this._attachBtnHandler(d.nextBtnClassName,"next");this._attachBtnHandler(d.playBtnClassName,"play");this._attachBtnHandler(d.stopBtnClassName,
"stop");this.bind("wp-slideshow-play",function(){this.$element.addClass(d.playingClassName)});this.bind("wp-slideshow-stop",function(){this.$element.removeClass(d.playingClassName)})},_first:function(){this.slides.showPanel(0)},_last:function(){var a=this.slides;a.showPanel(a.$element.length-1)},_previous:function(){var a=this.slides,d=a.activeIndex;a.showPanel((d<1?a.$element.length:d)-1)},_next:function(){var a=this.slides,d=a.activeIndex,b=(d+1)%a.$element.length;(!this.isPlaying()||this._isLoaded(d)&&
this._isLoaded(b))&&a.showPanel(b)},_goTo:function(){this.slides.showPanel.apply(this.slides,arguments)},_isLoaded:function(a){if(this._csspIsImageSlideShow&&(a=b(this.slides.$element[a]).find("img"),a.length>0&&(a.hasClass(this.options.imageIncludeClassName)||!a[0].complete)))return!1;return!0}})})(jQuery,WebPro,window,document);
(function(b,c){c.Widget.ContentSlideShow.fadingTransitionPlugin={defaultOptions:{transitionDuration:500},initialize:function(a,d){var f=this;b.extend(d,b.extend({},f.defaultOptions,d));a.bind("attach-behavior",function(){f.attachBehavior(a)})},attachBehavior:function(a){var d=this,f=a.slides,c=f.$element,h=f.activeIndex;f.bind("wp-panel-show",function(b,f){d.handleShowSlide(a,f)}).bind("wp-panel-hide",function(b,f){d.handleHideSlide(a,f)});for(f=0;f<c.length;f++)if(f!==h)c[f].style.display="none";
if(Muse.Browser.Features.Touch){var i=a.options.transitionDuration;a._ftpSwipeNoInterrupt=!1;c.each(function(){var f=b(this);f.data("opacity",f.css("opacity"));f.swipe({triggerOnTouchEnd:!0,allowPageScroll:"vertical",threshold:75,swipeStatus:function(b,f,h,j){a.stop();if(f=="move"&&(h=="left"||h=="right"))d._scrollTo(a,-1,j*(h=="left"?1:-1),0);else if(f=="cancel")d._scrollTo(a,a.slides.activeIndex,0,i);else if(f=="end"&&(h=="left"||h=="right")){var b=a.slides.activeIndex,o;h=="right"?o=b-1<0?c.length-
1:b-1:h=="left"&&(o=b+1>c.length-1?0:b+1);d._scrollTo(a,o,0,i)}}})})}},handleShowSlide:function(a,d){var f=b(d.panel),c=!1,h=function(){c||(c=!0,f.show().css("opacity",""))},i=setTimeout(h,a.options.transitionDuration+10);f.stop(!1,!0).fadeIn(a.options.transitionDuration,function(){clearTimeout(i);h()})},handleHideSlide:function(a,d){var f=b(d.panel),c=!1,h=function(){c||(c=!0,f.hide().css("opacity",""))},i=setTimeout(h,a.options.transitionDuration+10);f.stop(!1,!0).fadeOut(a.options.transitionDuration,
function(){clearTimeout(i);h()})},_scrollTo:function(a,d,f,c){if(!a._ftpSwipeNoInterrupt){var h=a.slides.$element,i=a.slides.activeIndex,j=d==-1;d==-1&&(d=f<0?i-1<0?h.length-1:i-1:i+1>h.length-1?0:i+1);var m=b(h[i]),l=b(h[d]);if(!j&&f==0||i==d){a._ftpSwipeNoInterrupt=!0;var k=0,n=!1,o=function(){if(!n&&(n=!0,l.show().css("opacity",""),d!=i&&a.slides.showPanel(d),++k==h.length))a._ftpSwipeNoInterrupt=!1};if(l.css("opacity")!=l.data("opacity")){var p=setTimeout(o,c+10);l.stop(!1,!0).animate({opacity:l.data("opacity")},
c,function(){clearTimeout(p);o()})}else o();h.each(function(f){var i=b(this),j=!1,m=function(){if(!j&&(j=!0,i.hide().css("opacity",""),++k==h.length))a._ftpSwipeNoInterrupt=!1},l;f!=d&&(i.css("display")!="none"&&i.css("opacity")!=0?(l=setTimeout(m,c+10),i.stop(!1,!0).animate({opacity:0},c,function(){clearTimeout(l);m()})):m())})}else f=Math.abs(f),j=m.width(),f>j&&(f=j),f=l.data("opacity")*(f/j),j=m.data("opacity")*(1-f),m.stop(!1,!0).animate({opacity:j},c),l.stop(!1,!0).show().animate({opacity:f},
c)}}};c.Widget.ContentSlideShow.filmstripTransitionPlugin={defaultOptions:{transitionDuration:500,transitionStyle:"horizontal"},initialize:function(a,d){var f=this;b.extend(d,b.extend({},f.defaultOptions,d));a.bind("attach-behavior",function(){f.attachBehavior(a)})},attachBehavior:function(a){var b=this,f=a.options,c=f.transitionStyle==="horizontal",h=a.slides,i=h.$element,j=a._findWidgetElements("."+f.clipClassName),f=a._findWidgetElements("."+f.viewClassName),m=j.width(),l=j.height(),k=c?m:l,n=
0,o={top:"0",left:"0"};j.css("position")!=="absolute"&&j.css("position","relative");f.css("position")!=="absolute"&&(o.position="relative");a._fstp$Clip=j;a._fstp$View=f;a._fstpStyleProp=c?"left":"top";a._fstpStylePropZero=c?"top":"left";h.bind("wp-panel-show",function(f,c){b._goToSlide(a,c.panel)});a._fstpRequestType=null;a.bind("wp-slideshow-before-previous wp-slideshow-before-next",function(b){a._fstpRequestType=b.type.replace(/.*-/,"");a._fstpOldActiveIndex=a.slides.activeIndex}).bind("wp-slideshow-previous wp-slideshow-next",
function(){a._fstpRequestType=null;a._fstpOldActiveIndex=-1});for(var j=a._fstpStyleProp,p=a._fstpStylePropZero,q=0;q<i.length;q++){var t=i[q].style;t[p]="0";t[j]=n+"px";t.margin="0";t.position="absolute";n+=k}o[c?"width":"height"]=n+"px";o[c?"height":"width"]=(c?l:m)+"px";h.activeElement||(o[j]=(c?m:l)+"px",o[p]="0");o.overflow="visible";f.css(o);b._goToSlide(a,h.activeElement)},_goToSlide:function(a,d){if(a){var f=b(d),c=a._fstp$View,h=a._fstpStyleProp,i=h==="left"?"offsetLeft":"offsetTop",j=h===
"left"?"offsetWidth":"offsetHeight",m=d?-d[i]:a._fstp$Clip[0][j],l={};l[h]=m+"px";var k=a._fstpRequestType,n=a._fstpOldActiveIndex;if(k&&n!==-1){var o=a.slides.activeIndex,p=a.slides.$element.length-1;if(o!==n){var q=0;k==="previous"&&n===0&&o===p?q=-d[j]:k==="next"&&n===p&&o===0&&(k=a.slides.$element[n],q=k[i]+k[j]);q&&(l[h]=-q+"px",f.css(h,q+"px"))}}c.stop(!1,!0).animate(l,a.options.transitionDuration,function(){q&&(f.css(h,-m+"px"),c.css(h,m+"px"))})}}};c.Widget.ContentSlideShow.swipeTransitionPlugin=
{defaultOptions:{transitionDuration:500,transitionStyle:"horizontal"},initialize:function(a,d){var f=this;b.extend(d,b.extend({},f.defaultOptions,d));a.bind("attach-behavior",function(){f.attachBehavior(a)})},attachBehavior:function(a){var b=this,f=a.options,c=f.transitionStyle==="horizontal",h=a.slides,i=h.$element,j=a._findWidgetElements("."+f.clipClassName),m=a._findWidgetElements("."+f.viewClassName),f=j.width(),l=j.height(),k=c?f:l,f=0,l={top:"0",left:"0"};j.css("position")!=="absolute"&&j.css("position",
"relative");m.css("position")!=="absolute"&&(l.position="relative");a._fstp$Clip=j;a._fstp$View=m;a._fstpStyleProp=c?"left":"top";a._fstpStylePropZero=c?"top":"left";h.bind("wp-panel-show",function(){b._scrollTo(a,a.slides.activeIndex*k,a.options.transitionDuration)});a._fstpRequestType=null;a.bind("wp-slideshow-before-previous wp-slideshow-before-next",function(b){a._fstpRequestType=b.type.replace(/.*-/,"");a._fstpOldActiveIndex=a.slides.activeIndex}).bind("wp-slideshow-previous wp-slideshow-next",
function(){a._fstpRequestType=null;a._fstpOldActiveIndex=-1});for(var j=a._fstpStyleProp,n=a._fstpStylePropZero,o=0;o<i.length;o++){var p=i[o].style;p[n]="0";p[j]=f+"px";p.margin="0";p.position="absolute";f+=k}l[c?"width":"height"]=f+"px";l[c?"height":"width"]=k+"px";l.overflow="visible";m.css(l);var q=a.options.transitionDuration;m.swipe({triggerOnTouchEnd:!0,allowPageScroll:c?"vertical":"horizontal",threshold:75,swipeStatus:function(f,i,h,j){a.stop();if(i=="move"&&(c&&(h=="left"||h=="right")||!c&&
(h=="up"||h=="down")))f=k*a.slides.activeIndex+j*(h=="left"||h=="up"?1:-1),b._scrollTo(a,f,0);else if(i=="cancel")f=k*a.slides.activeIndex,b._scrollTo(a,f,q);else if(i=="end"){var l;if(c&&h=="right"||!c&&h=="down")l=Math.max(a.slides.activeIndex-1,0);else if(c&&h=="left"||!c&&h=="up")l=Math.min(a.slides.activeIndex+1,m.children().length-1);f=k*l;b._scrollTo(a,f,q);l!=a.slides.activeIndex&&a.slides.showPanel(l)}}});b._scrollTo(a,h.activeElement?h.activeIndex*k:1*k,0)},_scrollTo:function(a,b,f){a._fstp$View.get(0).style[Muse.Utils.getCssVendorPrefix()+
"-transition-duration"]=(f/1E3).toFixed(1)+"s";var f=(b<0?"":"-")+Math.abs(b).toString(),c=a.options.transitionStyle==="horizontal",b=c?f:0,f=c?0:f;a._fstp$View.get(0).style[Muse.Utils.getCssVendorPrefix()+"-transform"]="translate3d("+b+"px,"+f+"px,0px)"}};c.Widget.ContentSlideShow.slideImageIncludePlugin={defaultOptions:{imageIncludeClassName:"wp-slideshow-slide-image-include",slideLoadingClassName:"wp-slideshow-slide-loading"},initialize:function(a,d){var f=this;b.extend(d,b.extend({},f.defaultOptions,
d));a._cssilLoader=new c.ImageLoader;a.bind("attach-behavior",function(){f._attachBehavior(a)})},_attachBehavior:function(a){for(var b=this,f=a._cssilLoader,c=a._findWidgetElements("."+a.options.slideClassName),h=c.length,i="."+a.options.imageIncludeClassName,j=a.options.slideLoadingClassName,m=function(f,c,g,h){b._handleImageLoad(a,f,c,g,h)},l=0;l<h;l++){var k=c.eq(a._shuffleArray?a._shuffleArray[l]:l),n=k.find(i);if(ele=n[0]){var o=n.data("src")||ele.href;if(o)n={id:ele.id||"",classAttr:ele.className||
"",alt:ele.alt,width:n.data("width"),height:n.data("height"),$ele:n,$slide:k},ele.style.visibility="hidden",f.add(o,{callback:m,data:n}),k.addClass(j)}}a._cssilLoader.start()},_handleImageLoad:function(a,d,f,c,h){d=b('<img id="'+(h.id||"")+'" class="'+h.classAttr+'" alt="'+h.alt+'" src="'+d+'" width="'+(h.width||f)+'" height="'+(h.height||c)+'">');d.removeClass(a.options.imageIncludeClassName);h.$ele.replaceWith(d);h.$slide.removeClass(a.options.slideLoadingClassName);a.isPlaying()&&a.slides.$element[a.slides.activeIndex]==
h.$slide[0]&&a._startTimer()}};c.Widget.ContentSlideShow.shufflePlayPlugin={defaultOptions:{randomDefaultIndex:!0},initialize:function(a,d){var f=this;b.extend(d,b.extend({},f.defaultOptions,d));a._shuffleArray=[];a._shuffleNextDict={};a._realNext=a._next;a._next=function(){f._handleNext(a)};a._shufflePlayCount=0;a.bind("before-attach-behavior",function(){f._reshuffle(a);if(d.randomDefaultIndex&&typeof d.defaultIndex==="undefined")a.options.defaultIndex=a._shuffleArray[0]})},_fisherYatesArrayShuffle:function(a){if(a&&
a.length)for(var b=a.length;--b;){var f=Math.floor(Math.random()*(b+1)),c=a[f];a[f]=a[b];a[b]=c}},_reshuffle:function(a){var b=a._shuffleArray,f={},c=a.slides?a.slides.$element.length:a._findWidgetElements("."+a.options.slideClassName).length;if(b.length!==c)for(var h=b.length=0;h<c;h++)b[h]=h;this._fisherYatesArrayShuffle(b);for(h=0;h<c;h++)f[b[h]]=b[(h+1)%c];a._shuffleNextDict=f;a._shufflePlayCount=0},_handleNext:function(a){if(a.isPlaying()){var b=a.slides.activeIndex,f=a._shuffleNextDict[b]||
0;a._isLoaded(b)&&a._isLoaded(f)&&(a._goTo(f),++a._shufflePlayCount>=a.slides.$element.length&&this._reshuffle(a))}else a._realNext()}}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.Form",c.Widget,{_widgetName:"form",defaultOptions:{validationEvent:"blur",errorStateSensitivity:"low",ajaxSubmit:!0,fieldWrapperClass:"field",formErrorClass:"form-error",formSubmittedClass:"form-submitted",formDeliveredClass:"form-delivered",focusClass:"focus",notEmptyClass:"not-empty",emptyClass:"empty",validClass:"valid",invalidClass:"invalid",requiredClass:"required"},validationTypes:{"always-valid":/.*/,email:/^[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i,
alpha:/^[A-z\s]+$/,numeric:/^[0-9]+$/,phone:/^([0-9])?(\s)?(\([0-9]{3}\)|[0-9]{3}(\-)?)(\s)?[0-9]{3}(\s|\-)?[0-9]{4}(\s|\sext|\sx)?(\s)?[0-9]*$/,captcha:function(a){return a.data("captchaValid")},time:function(a){var a=a.find("input, textarea"),b=a.val().replace(/[^0-9:APM]/g,"");if(b.indexOf(":")!=-1&&b.match(/:/).length==1){var f=b.split(":"),c=parseInt(f[0]),f=parseInt(f[1]);if(c<0||c>24)return!0;if(f<0||f>59)return!0}else return!1;a.val(b);return!0}},_transformMarkup:function(){var a=this;a.hasCAPTCHA=
!1;this.$element.find("."+this.options.fieldWrapperClass).each(function(){var d=b(this);if(d.attr("data-type")=="captcha")a.hasCAPTCHA=!0,d.find('input[name="CaptchaV2"]').remove(),d.find('input[name="muse_CaptchaV2"]').attr("name","CaptchaV2")})},_extractData:function(){this.event=this.options.validationEvent;this.errorSensitivity=this.options.errorStateSensitivity;this.classNames={focus:this.options.focusClass,blur:this.options.emptyClass,keydown:this.options.notEmptyClass}},_attachBehavior:function(){var a=
this;this.$element.find("input, textarea").each(function(){var d=b(this);d.val()!=""&&d.removeClass(a.options.emptyClass)});this.$element.find("."+this.options.fieldWrapperClass).each(function(){var d=b(this);d.attr("data-type")=="captcha"&&(d.data("captchaValid",!1),d.find('input[name="CaptchaV2"]').keyup(function(){var f=b(this).val(),c=d.find('input[name="CaptchaHV2"]').val();a._validateCaptcha(c,f,function(b){d.data("captchaValid",b);d.data("error-state")&&a.errorSensitivity=="high"&&a._validate(d)})}));
d.find("input, textarea").val()!=""&&d.addClass(a.classNames.keydown)});this.$element.find("input, textarea").bind("focus blur keydown change propertychange",function(d){var c=a.classNames[d.type],g=a.classNames.focus,h=a.classNames.keydown,i=a.classNames.blur,j=b(this),m=j.closest("."+a.options.fieldWrapperClass);switch(d.type){case "focus":m.addClass(c).removeClass(i);break;case "blur":m.removeClass(g);j.val()==""&&m.addClass(c).removeClass(h);break;case "keydown":m.addClass(c).removeClass(i);break;
case "change":case "propertychange":j.val()!=""?m.addClass(h).removeClass(i):m.addClass(i).removeClass(h)}});switch(this.event){case "blur":case "keyup":this.$element.find("."+this.options.fieldWrapperClass+" input, ."+this.options.fieldWrapperClass+" textarea").bind(this.event,function(){a._validate(b(this).closest("."+a.options.fieldWrapperClass))});case "submit":this.$element.submit(function(d){var c=!0,g=a.$element.find("."+a.options.fieldWrapperClass).length-1;a.$element.find("."+a.options.fieldWrapperClass).each(function(h){if((c=
a._validate(b(this))?c:!1)&&h==g&&a.options.ajaxSubmit)d.preventDefault(),a._submitForm();c||d.preventDefault()})})}},_validateCaptcha:function(a,d,c){d.length!=6?c(!1):b.get("/ValidateCaptcha.ashx",{key:a,answer:d},function(a){c(a=="true")})},_submitForm:function(){var a=this,d=this.options.formSubmittedClass,c=this.options.formDeliveredClass,g=this.options.formErrorClass,h=d+" "+c+" "+g,i=this.$element.find("input[type=submit], button");b.ajax({url:this.$element.attr("action"),type:"post",data:this.$element.serialize(),
beforeSend:function(){a.$element.removeClass(h);a.$element.addClass(d);a.$element.find("."+a.options.fieldWrapperClass).removeClass(a.options.focusClass);i.attr("disabled","disabled")},complete:function(h){h&&h.responseText&&h.responseText.indexOf('"success": true')>0?(a.$element.addClass(c).removeClass(d),a.$element.find("input:not([type=submit]), textarea").each(function(){var d=b(this);d.val("");a.hasCAPTCHA&&d.attr("disabled","disabled")})):a.$element.addClass(g).removeClass(d);a.hasCAPTCHA||
i.removeAttr("disabled")}})},_validate:function(a){var b=a.attr("data-type")||"always-valid",c=a.find("input, textarea"),g=this.validationTypes[b],b=a.attr("data-required")==="true",h=c.val()=="",c=g instanceof RegExp?Boolean(c.val().match(g)):g(a);if(b&&h)return this._switchState("required",a);if(!c)return this._switchState("invalid",a);return this._switchState("valid",a)},_switchState:function(a,b){function c(){j._validate(b)}var g=this.options.validClass,h=this.options.invalidClass,i=this.options.requiredClass;
b.removeClass(g+" "+h+" "+i);if(a=="required"||a=="invalid"){a=="invalid"?b.addClass(h):b.addClass(i);if(this.errorSensitivity!="low"){var j=this,g=this.errorSensitivity=="high"?"keyup":"blur";b.data("error-state")||(b.data("error-state",!0),b.find("input, textarea").bind(g,c))}return!1}b.data("error-state")&&(this.errorSensitivity=="high"?this.event!="keyup"&&b.data("error-state",!1).find("input, textarea").unbind("keyup",c):this.errorSensitivity=="medium"&&this.event!="blur"&&b.data("error-state",
!1).find("input, textarea").unbind("blur",c));b.addClass(g);return!0}});b.fn.wpForm=function(a){new c.Widget.Form(this,a);return this}})(jQuery,WebPro,window,document);
