#!/usr/bin/perl

use lib qw(lib);
use LWP::UserAgent;
use Getopt::Long;
use strict;
use Data::Dumper qw(Dumper);

eval "use LWP::Debug qw(+);";			# turn on debugging

# DEFAULT SSL VERSION
$ENV{HTTPS_VERSION} = '3';

$ENV{HTTPS_DEBUG} = 1;
$ENV{HTTPS_CERT_FILE} = 'certs/webapi.zoovy.com.cer';
$ENV{HTTPS_KEY_FILE} = 'certs/webapi.zoovy.com.key';

## CA CERT PEER VERIFICATION
#$ENV{HTTPS_CA_FILE}   = 'certs/intuit.crt';
#$ENV{HTTPS_CA_DIR}    = 'certs/';

my $url = 'https://webapps.quickbooks.com/j/AppGateway';

my $content = qq~<?xml version="1.0"?>
<!DOCTYPE QBXML PUBLIC '-//INTUIT//DTD QBXML QBO 2.0//EN' 'http://apps.quickbooks.com/dtds/qbxmlops20.dtd'>
<QBXML>
<SignonMsgsRq>
<SignonAppCertRq requestID="1234">
<ClientDateTime>2005-03-02T10:00:00</ClientDateTime>
<ApplicationLogin>www.zoovy.com</ApplicationLogin>
<ConnectionTicket>TGT-180-a\$iS7X3Nj8CxyUrVtTP90g</ConnectionTicket>
<InstallationID>1</InstallationID>
<Language>English</Language>
<AppID>79496516</AppID>
<AppVer>1.00</AppVer>
</SignonAppCertRq>
</SignonMsgsRq>
</QBXML>
~;

use XML::Parser;
my $p = new XML::Parser;
$p->parse($content);

my $ua = new LWP::UserAgent;
$ua->timeout(15);
my $head = new HTTP::Headers;
my $req = new HTTP::Request('POST', $url, $head, $content);
my $res = $ua->request($req);
print Dumper($res);



exit;

#<?xml version="1.0"?>
#<!DOCTYPE QBXML PUBLIC '-//INTUIT//DTD QBXML QB0 2.0//EN'
#'http://apps.quickbooks.com/dtds/qbxmlops20.dtd'>
#<QBXML>
#<SignonMsgsRq>
#<SignonDesktopRq>
#<ClientDateTime>2005-03-02T10:47:03</ClientDateTime>
#<ApplicationLogin>dtVBOESDKTest</ApplicationLogin>
#<ConnectionTicket></ConnectionTicket>
#<Language>English</Language>
#<AppID>54442418</AppID>
#<AppVer>1.0</AppVer>
#</SignonDesktopRq></SignonMsgsRq></QBXML>
#$opt_cafile && ( $ENV{HTTPS_CA_FILE} = $opt_cafile );
#$opt_cadir  && ( $ENV{HTTPS_CA_DIR} = $opt_cadir   );

print $content;
# exit;
